export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	CREATE_CART: 'CREATE_CART',
	SET_CART_DATA: 'SET_CART_DATA',
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	CLEAR_CART: 'CLEAR_CART',
	UPDATE_COUNT_IN_CART: 'UPDATE_COUNT_IN_CART',
};
